name: Deployment test
on:
  push:
env:
  env_name: ${{ github.ref_name == 'main' && 'production' || 'developpement' }}
jobs:
  build:
    runs-on: ubuntu-latest
    environment: developpement
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install nbconvert
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert
      - name: display current environnement
        run : |
          echo $env_name
          echo $env_name
      - name: display current directory
        run : |
          ls -la
      - name: Convert notebook
        run: jupyter nbconvert --to python traffic.ipynb
      - name: Upload python script
        uses: actions/upload-artifact@v4
        with:
          name: traffic.py
          path: traffic.py
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: developpement
    env:
      prefix: ${{ vars.PREFIX }}
    steps:
      - name: Download python script from build
        uses: actions/download-artifact@v4
        with:
          name: traffic.py
      - name: Set up AWS credentials
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          mkdir -p ~/.aws
          touch ~/.aws/credentials
          echo "[default]
          aws_access_key_id = $AWS_ACCESS_KEY_ID
          aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" > ~/.aws/credentials
      - name: Display prefix
        run: |
         echo $prefix
         echo $env_name 
      - name: Upload to S3
        run: aws s3 cp traffic.py s3://$prefix/${{secrets.S3_BUCKET}}/traffic_${GITHUB_SHA}.py --region us-east-1
